project: "PhenProj"
experiment_name: "outdim3_nonlin_pred_head_abcd_cog"
hypothesis: "-"

# Model dimensions
input_dim_feat: 400
output_dim_feat: 200
hidden_dim: 100
input_dim_target: 1
output_dim_target: 50

# MatAutoencoder options
skip_enc1: False
ReEig: False

# Pretrained models options
mat_ae_pretrained: False
target_ae_pretrained: False
pretrained_mat_ae_exp: "internal_mat_ae_abcd"
pretrained_target_ae_exp: "target_ae"
best_mat_ae_fold: 4
best_target_ae_fold: 1
synth_exp: False

# Training parameters
multi_gpu: True
num_epochs: 100
batch_size: 28
n_runs: 1 # set 1 if some part of the model is pretrained (the test set should be the same)
lr: 0.001
weight_decay: 0
dropout_rate: 0
scheduler_patience: 10
test_ratio: 0.3 # makes no difference if some part of the model is pretrained
train_ratio: 1.0
log_gradients: True
clip_grad: True

# test options
external_test_mode: False # relevant if no part of the model is pretrained
test_scanners:
    - "GE MEDICAL SYSTEMS_DISCOVERY MR750"
    - "Philips Medical Systems_Achieva dStream"
    - "Philips Medical Systems_Ingenia"

# Contrastive loss parameters
SupCon_kernel: cauchy
SupConLoss_on_mat: False

## feature proj vs. targets
pft_base_temperature: 0.07
pft_temperature: 0.07
pft_sigma: 1
pft_reg_term: 0.01

## target proj vs. targets
ptt_base_temperature: 0.07
ptt_temperature: 0.07
ptt_sigma: 1
ptt_reg_term: 0.01

# Other losses
feature_autoencoder_crit: Norm  # Options: Norm, MSE, LogEuclidean
joint_embedding_crit: cosine  # Options: Norm, MSE, cosine
target_decoding_crit: MSE  # Options: Norm, MSE
huber_delta: 10

# Data
augmentation: None
mat_threshold: 0
# Paths for data
dataset_path: "/gpfs3/well/margulies/users/cpy397/contrastive-learning/data/abcd_dataset_400parcels_1.nc"
targets:
    - nihtbx_totalcomp_agecorrected
standardize_targets: False

# Directory for saving results
work_dir: "/gpfs3/well/margulies/users/cpy397/contrastive-learning"
reconstructed_dir : recon_mat
embedding_dir : embeddings
model_weight_dir : saved_models
output_dir: "/gpfs3/well/margulies/users/cpy397/contrastive-learning/results"