project: "PretrainMatAE"
experiment_name: "ext_sup_reduced_mat_ae_abcd"

hydra:
  run:
    dir: /data/parietal/store/work/vshevche/outputs/${now:%H-%M-%S}/${hydra.job.name}

hypothesis: "-"
# Training parameters
multi_gpu: True
num_epochs: 200
batch_size: 64
kfolds: 5
lr: 0.001
weight_decay: 0
dropout_rate: 0
scheduler_patience: 10
test_size : 0.3
seed : 42
log_gradients: True
clip_grad: True
synth_exp: False

# test options
external_test_mode: True
test_scanners:
    - "GE MEDICAL SYSTEMS_DISCOVERY MR750"
    - "Philips Medical Systems_Achieva dStream"
    - "Philips Medical Systems_Ingenia"

# enhancements
ReEig: False
skip_enc1: False

# Model dimensions
input_dim_feat: 100
hidden_dim : 128
output_dim_feat: 100
output_dim_target: 64
input_type: "reduced_mat" # Options: matrices, targets

# Loss function and optimizer
loss_function: Norm  # Options: LogEuclidean, Norm, MSE
supcon_base_temperature: 0.03
supcon_temperature: 0.03
supcon_sigma: 1
supcon_reg_term: 0.01
SupCon_kernel: cauchy

# modify manually if test is run as a separate job
best_fold: 1

# Paths for data
dataset_path: "/data/parietal/store/work/vshevche/data/abcd_dataset_400parcels.nc"
targets:
    - nihtbx_totalcomp_agecorrected # used is supervised

# Directory for saving results
work_dir: "/data/parietal/store/work/vshevche"
embedding_dir : embeddings
reconstructed_dir : recon_mat
model_weight_dir : saved_models
output_dir: "/data/parietal/store/work/vshevche/results"