project: "PretrainMatAE_SCZ"
experiment_name: "mat_ae_test_size0.2"

hypothesis: "-"
# Training parameters
multi_gpu: True
num_epochs: 10
batch_size: 32
kfolds: 2
lr: 0.001
weight_decay: 0
dropout_rate: 0
scheduler_patience: 10
test_size : 0.2
seed : 42

# non-linearity enhancements
ReEig: False
skip_enc1: True

# Model dimensions
input_dim_feat: 400
output_dim_feat: 50

# Loss function and optimizer
loss_function: Norm  # Options: LogEuclidean, Norm, MSE

# modify manually if test is run as a separate job
best_fold: 5

# Paths for data
dataset_path: "/lustre/fswork/projects/rech/ftj/commun/contrastive-phenotypes/data/scz_dataset_400parcels.nc"  
targets:
    - age

# Directory for saving results
work_dir: "/lustre/fswork/projects/rech/ftj/commun/contrastive-phenotypes"
reconstructed_dir : recon_mat
model_weight_dir : saved_models
output_dir: "/lustre/fswork/projects/rech/ftj/commun/contrastive-phenotypes/results"
