# conf_feat_ae_skip_conn_optuna/sweep/optuna.yaml
defaults :
- override hydra/sweeper : optuna

hydra:
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    params:
      n_trials: 10  # Total number of hyperparameter trials
      study_name: "autoencoder_optimization"  # Moved outside 'study' to match BasicSweeperConf
      direction: minimize  # Objective to minimize validation loss
      sampler:
        _target_: optuna.samplers.TPESampler  # Tree-structured Parzen Estimator sampler
        seed: 42
      pruner:
        _target_: optuna.pruners.MedianPruner  # Pruner to eliminate unpromising trials
        n_startup_trials: 5
        n_warmup_steps: 10
      storage: "sqlite:///data/parietal/store2/work/mrenaudi/contrastive-reg-3/hydra/${branch_name}/optuna_study.db"  # Corrected path format
      n_jobs: -1  # Number of parallel jobs (-1 uses all available cores)
      timeout: 7200  # Maximum time (in seconds) per trial
      catch: [ValueError, RuntimeError]  # Exceptions to catch during trials
      params:
        lr:
          type: loguniform
          low: 1e-5
          high: 1e-1
