project: "PretrainTargetAE"
experiment_name: "out2_target_ae"
hypothesis: "-"
# Training parameters
multi_gpu: True
num_epochs: 100
batch_size: 32
kfolds: 5
lr: 0.001
weight_decay: 0
dropout_rate: 0
scheduler_patience: 10
seed: 42
test_size: 0.2
input_type: "targets" # Options: matrices, targets
# Model dimensions
input_dim_target: 1
hidden_dim: 1000
output_dim_target: 2

# Loss function and optimizer
loss_function: MSE  # Options: LogEuclidean, Norm, MSE

# Paths for data
dataset_path: "/gpfs3/well/margulies/users/cpy397/contrastive-learning/ABCD/abcd_dataset_400parcels.nc"  
targets:
    - cbcl_scr_syn_totprob_r

# Directory for saving results
work_dir: "/gpfs3/well/margulies/users/cpy397/contrastive-learning"
model_weight_dir : saved_models
recon_targets_dir : recon_targets
output_dir: "/gpfs3/well/margulies/users/cpy397/contrastive-learning/results"