defaults:
  - override hydra/sweeper: optuna
  - override hydra/job_logging: disabled

project: "feature autoencoder optuna"
experiment_name: "test optuna"
hypothesis: "first test on optuna"

# Training parameters
multi_gpu: False
num_epochs: 1
batch_size: 32
lr : 0.001
# Default learning rate; to be overridden by sweeper
weight_decay: 0
dropout_rate: 0
kfolds: 5
ReEig: False
skip_enc1: True
scheduler_patience: 10

# Model dimensions
input_dim_feat: 100
output_dim_feat: 10

# Loss function and optimizer
loss_function: Norm # Options: LogEuclidean, Norm

# Paths for data
dataset_path: "/data/parietal/store2/work/mrenaudi/contrastive-reg-3/dataset_100parcels_with_age_2.nc"
targets:
- benton_faces_total

# Directory for saving results
original_dir: original
reconstructed_dir: reconstructed
tensorboard_dir: tensorboard
model_weight_dir: weights
branch_name: feat_ae_skip_conn
output_dir: "/data/parietal/store2/work/mrenaudi/contrastive-reg-3/hydra/${branch_name}"

# Hydra-Optuna sweeper configuration
hydra:
  sweeper:
    sampler:
      seed: 123
    direction: minimize
    study_name: feature_autoencoder_study
    storage: null
    n_trials: 20
    n_jobs: 1
    params:
      lr: tag(log, interval(1e-5, 1e-1))
